# GoToGitHub CI — shellcheck on push/PR
name: Lint

on:
  push:
    branches: [main, dev-*]
    paths:
      - 'fetch.sh'
      - 'install.sh'
  pull_request:
    branches: [main]
    paths:
      - 'fetch.sh'
      - 'install.sh'

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck on fetch.sh
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          additional_files: fetch.sh

      - name: Run ShellCheck on install.sh
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          name: install_sh
          additional_files: install.sh